CREATE TABLE mytable(
  nr integer primary key autoincrement 
  ,name         string
  ,organisation string
  ,budget       INTEGER
  ,status       string
);
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Echo Expansion','Orbital Systems',108150,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Vertex Expansion','TechCorp',437873,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Lyra Network','Skyline Industries',33951,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Horizon Program','CrystalPeak Institute',394094,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nimbus Protocol','TechCorp',51514,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Solara Platform','Orbital Systems',904703,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Vortex Program','Pioneer Group',451036,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Mirage Platform','FutureLabs',444598,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Helix Network','NovaWorks',189736,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Horizon Protocol','Pioneer Group',41953,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Lyra Protocol','TechCorp',53768,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Helix Project','CrystalPeak Institute',1966,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Lyra Program','TechCorp',185677,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Orion Protocol','Horizon Dynamics',416569,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Mirage System','Skyline Industries',650000,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Vortex Project','Orbital Systems',517819,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Titan Network','TechCorp',178607,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Vortex Platform','FutureLabs',69963,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nimbus System','Skyline Industries',706339,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Orion Project','NovaWorks',547949,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Phoenix System','BlueWave Foundation',444439,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Zenith System','Pioneer Group',850967,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Solara Initiative','Horizon Dynamics',197181,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nova Project','BlueWave Foundation',19131,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Orion Expansion','BlueWave Foundation',383353,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Titan Network','Orbital Systems',01997,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Zenith System','BlueWave Foundation',1340,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Apex Expansion','Skyline Industries',3174,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Spectra Program','TechCorp',785486,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Titan Network','FutureLabs',53655,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Pulse Initiative','FutureLabs',366480,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Echo Initiative','FutureLabs',411653,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Orion Platform','FutureLabs',637698,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nebula Program','TechCorp',666857,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Vortex Program','TechCorp',731599,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Mirage Expansion','Pioneer Group',31400,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nimbus Expansion','Horizon Dynamics',418675,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Phoenix Project','CrystalPeak Institute',66,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Pulse Program','TechCorp',67999,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Solara Network','SilverGate Consortium',500058,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Phoenix Protocol','Horizon Dynamics',13537,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Helix Project','CrystalPeak Institute',10757,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Apex System','Horizon Dynamics',796568,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nimbus System','Horizon Dynamics',896311,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nebula Expansion','BlueWave Foundation',138109,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Quantum Program','CrystalPeak Institute',79041,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Apex Program','Skyline Industries',737758,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nimbus Project','BlueWave Foundation',454399,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Solara Project','Pioneer Group',40617,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Phoenix Initiative','CrystalPeak Institute',997763,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nova Platform','TechCorp',735835,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Phoenix Program','NovaWorks',35953,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Echo System','Orbital Systems',443894,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Titan Expansion','FutureLabs',10783,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Vortex Network','BlueWave Foundation',390885,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Lyra Initiative','TechCorp',53674,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Lyra Platform','TechCorp',538598,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Orion Initiative','TechCorp',541914,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Lyra Program','CrystalPeak Institute',173614,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Solara Network','BlueWave Foundation',179044,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Spectra System','NovaWorks',33949,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Vortex Protocol','Horizon Dynamics',44807,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Pulse System','Horizon Dynamics',406774,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nova Project','Orbital Systems',049,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Zenith Platform','Orbital Systems',1443,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Solara Project','TechCorp',33876,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Helix Protocol','Horizon Dynamics',444516,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Vortex Platform','Horizon Dynamics',940848,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Phoenix System','FutureLabs',1185,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Vortex Protocol','Horizon Dynamics',669140,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nimbus Initiative','TechCorp',516158,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Mirage Platform','BlueWave Foundation',371894,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Echo Initiative','Horizon Dynamics',373355,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Mirage Network','NovaWorks',41453,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Lyra Platform','Pioneer Group',343110,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Mirage Initiative','Orbital Systems',0749,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Apex Program','Horizon Dynamics',384586,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Horizon Protocol','NovaWorks',406,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Astra Project','Horizon Dynamics',719149,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Lyra Platform','CrystalPeak Institute',05576,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Vertex Initiative','Orbital Systems',86033,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Solara Initiative','Horizon Dynamics',467333,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Vertex Platform','SilverGate Consortium',813047,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Titan System','Skyline Industries',19414,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Orion Project','FutureLabs',414154,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Zenith Platform','CrystalPeak Institute',58616,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Lyra Network','Pioneer Group',7506,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Phoenix Platform','FutureLabs',31716,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Phoenix Program','Pioneer Group',7336,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nebula System','Skyline Industries',439899,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Zenith System','BlueWave Foundation',65190,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Quantum Network','Horizon Dynamics',354186,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Horizon Expansion','NovaWorks',360714,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Vertex System','Orbital Systems',354038,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Horizon Protocol','BlueWave Foundation',413636,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Titan Project','FutureLabs',396360,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Lyra System','FutureLabs',58354,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nebula System','Horizon Dynamics',390433,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Helix Network','Skyline Industries',331753,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Horizon Expansion','FutureLabs',35355,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Phoenix Expansion','Horizon Dynamics',45958,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Titan Platform','CrystalPeak Institute',999686,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Apex Expansion','CrystalPeak Institute',43877,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Spectra Protocol','NovaWorks',43714,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Spectra Program','Pioneer Group',116464,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Apex Protocol','Orbital Systems',603763,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Spectra System','Orbital Systems',846194,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Orion Program','Orbital Systems',48763,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Solara Project','Horizon Dynamics',37300,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Vertex Network','Orbital Systems',477616,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Zenith Platform','TechCorp',491574,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Vortex Protocol','Pioneer Group',699395,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nimbus System','Orbital Systems',501851,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Linear Development','TechCorp',696969,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Apex Program','Horizon Dynamics',853656,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Helix Project','NovaWorks',1476,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Phoenix Protocol','FutureLabs',380130,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Vertex Expansion','Pioneer Group',856951,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Phoenix System','CrystalPeak Institute',347070,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Apex Program','CrystalPeak Institute',435679,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Zenith Protocol','Pioneer Group',77880,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Apex Expansion','TechCorp',373541,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Pulse Platform','TechCorp',959330,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Solara Project','SilverGate Consortium',567078,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Spectra Network','BlueWave Foundation',73710,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Quantum Entanglement','TechCorp',75640,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Helix Platform','BlueWave Foundation',89394,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Pulse Platform','FutureLabs',0699,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Echo Network','CrystalPeak Institute',65605,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nimbus Platform','Horizon Dynamics',83336,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Quantum Project','BlueWave Foundation',98875,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Apex Program','Pioneer Group',16555,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Quantum Network','FutureLabs',100936,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Mirage Project','Horizon Dynamics',597808,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Solara Platform','SilverGate Consortium',17633,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nebula Protocol','CrystalPeak Institute',95613,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Lyra Program','Orbital Systems',464180,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Spectra Protocol','SilverGate Consortium',44545,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Quantum Program','Pioneer Group',10531,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Modern Warfare','TechCorp',8373,'delayed');
CREATE TABLE mytable(
   "Nm id"          integer primary key autoincrement 
  ,nr               INTEGER 
  ,EncryptAuthThing string
);
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (5,'aArjz521x#(94');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (69,'AAsUi307x6071');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (144,'aaSlH144x(788');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (155,'AAmjt314y2!53');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (51,'aAkMq669y#835');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (16,'AAsUi307x6071');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (85,'AAmjt314y2!53');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (55,'aAhIy141y@!74');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (91,'aaSlH144x(788');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (94,'AAmjt314y2!53');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (157,'aAhIy141y@!74');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (43,'aAhIy141y@!74');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (98,'Aabhf536x6)21');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (8,'AAsUi307x6071');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (156,'aAcYD911y$$26');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (10,'aArjz521x#(94');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (00,'Aabhf536x6)21');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (151,'AAsUi307x6071');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (90,'AARjy681x)281');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (109,'aAhIy141y@!74');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (108,'aAhIy141y@!74');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (9,'AAmjt314y2!53');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (139,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (14,'aAcYD911y$$26');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (186,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (59,'aaSlH144x(788');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (180,'Aabhf536x6)21');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (197,'AAsUi307x6071');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (185,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (147,'AAmjt314y2!53');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (53,'AAmjt314y2!53');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (100,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (184,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (138,'AAmjt314y2!53');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (110,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (165,'AAsUi307x6071');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (49,'aAkMq669y#835');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (13,'AAmjt314y2!53');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (33,'Aabhf536x6)21');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (67,'AARjy681x)281');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (176,'aAhIy141y@!74');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (14,'aAcYD911y$$26');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (150,'AAsUi307x6071');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (135,'AARjy681x)281');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (18,'aArjz521x#(94');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (79,'aAkMq669y#835');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (181,'aArjz521x#(94');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (74,'aaSlH144x(788');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (103,'aAkMq669y#835');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (10,'aAkMq669y#835');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (15,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (96,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (18,'AAsUi307x6071');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (179,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (84,'AAsUi307x6071');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (89,'AARjy681x)281');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (198,'AAsUi307x6071');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (5,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (65,'aAhIy141y@!74');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (160,'aAhIy141y@!74');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (105,'aAcYD911y$$26');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (41,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (15,'aaSlH144x(788');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (133,'aAhIy141y@!74');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (77,'AAsUi307x6071');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (154,'aaSlH144x(788');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (104,'aAcYD911y$$26');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (170,'aAkMq669y#835');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (101,'aAhIy141y@!74');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (50,'aaSlH144x(788');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (11,'aaSlH144x(788');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (1,'AARjy681x)281');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (118,'Aabhf536x6)21');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (71,'AARjy681x)281');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (174,'aAcYD911y$$26');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (130,'aArjz521x#(94');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (164,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (158,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (NULL,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (6,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (193,'Aabhf536x6)21');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (97,'Aabhf536x6)21');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (194,'AAmjt314y2!53');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (63,'AAmjt314y2!53');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (195,'aArjz521x#(94');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (17,'aaSlH144x(788');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (177,'aAcYD911y$$26');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (57,'aAkMq669y#835');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (131,'aAkMq669y#835');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (87,'aArjz521x#(94');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (6,'aAkMq669y#835');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (44,'aAkMq669y#835');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (183,'AAmjt314y2!53');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (111,'aAkMq669y#835');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (190,'AARjy681x)281');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (4,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (37,'AAmjt314y2!53');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (64,'Aabhf536x6)21');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (114,'aArjz521x#(94');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (1,'aArjz521x#(94');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (6,'aAcYD911y$$26');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (54,'aArjz521x#(94');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (NULL,'aAhIy141y@!74');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (5,'aArjz521x#(94');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (137,'aArjz521x#(94');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (0,'aArjz521x#(94');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (8,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (107,'aAkMq669y#835');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (31,'AAsUi307x6071');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (35,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (86,'AAsUi307x6071');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (40,'aAhIy141y@!74');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (4,'aArjz521x#(94');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (113,'AAsUi307x6071');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (36,'aAkMq669y#835');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (17,'aAhIy141y@!74');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (196,'AAmjt314y2!53');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (34,'aAhIy141y@!74');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (1,'aAcYD911y$$26');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (7,'Aabhf536x6)21');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (70,'aaSlH144x(788');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (73,'aArjz521x#(94');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (18,'aAkMq669y#835');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (47,'aAkMq669y#835');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (171,'aaSlH144x(788');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (166,'aAhIy141y@!74');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (75,'aAkMq669y#835');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (7,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (163,'Aabhf536x6)21');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (66,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (48,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (10,'AAsUi307x6071');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (99,'AAsUi307x6071');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (189,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (1,'AARjy681x)281');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (16,'Aabhf536x6)21');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (141,'aaSlH144x(788');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (4,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (83,'Aabhf536x6)21');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (45,'aAhIy141y@!74');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (16,'Aabhf536x6)21');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (9,'AAmjt314y2!53');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (191,'AARjy681x)281');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (187,'aaSlH144x(788');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (95,'AAsUi307x6071');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (143,'aAhIy141y@!74');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (3,'aaSlH144x(788');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (8,'aArjz521x#(94');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (30,'AARjy681x)281');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (168,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (3,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (178,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (134,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (145,'aaSlH144x(788');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (167,'aArjz521x#(94');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (159,'aArjz521x#(94');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (38,'AAsUi307x6071');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (140,'AAmjt314y2!53');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (80,'aAhIy141y@!74');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (153,'Aabhf536x6)21');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (9,'aAkMq669y#835');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (161,'AARjy681x)281');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (117,'Aabhf536x6)21');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (56,'aAhIy141y@!74');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (17,'aArjz521x#(94');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (93,'AARjy681x)281');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (188,'aAcYD911y$$26');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (199,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (13,'aaSlH144x(788');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (78,'Aabhf536x6)21');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (175,'aAhIy141y@!74');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (106,'AAsUi307x6071');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (116,'aAkMq669y#835');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (148,'aArjz521x#(94');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (149,'aArjz521x#(94');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (39,'aAhIy141y@!74');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (19,'aArjz521x#(94');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (68,'aAhIy141y@!74');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (3,'aAhIy141y@!74');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (146,'aaSlH144x(788');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (11,'aaSlH144x(788');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (115,'aaSlH144x(788');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (60,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (119,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (81,'AAmjt314y2!53');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (46,'aAhIy141y@!74');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (88,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (19,'aAcYD911y$$26');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (14,'Aabhf536x6)21');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (173,'aAhIy141y@!74');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (7,'aaSlH144x(788');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (76,'AAsUi307x6071');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (136,'AAsUi307x6071');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (169,'AAmjt314y2!53');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (13,'AAmjt314y2!53');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (61,'aArjz521x#(94');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (11,'aAhIy141y@!74');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (58,'AahKt174y!!63');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (15,'aaSlH144x(788');
INSERT INTO mytable(nr,EncryptAuthThing) VALUES (19,'aAkMq669y#835');
CREATE TABLE signers(
   id string,
   name string,
);
INSERT INTO mytable(id,name) VALUES ('RJZ554#(x','InnovativeAI3.7');
INSERT INTO mytable(id,name) VALUES ('SUI51206x','ZUS');
INSERT INTO mytable(id,name) VALUES ('SLH1647(x','Woodcrackers');
INSERT INTO mytable(id,name) VALUES ('MJT592!2y','JellyMansBureau');
INSERT INTO mytable(id,name) VALUES ('KMQ19118#','PortableHeadLight');
INSERT INTO mytable(id,name) VALUES ('HIY191!@y','Glass Inc.');
INSERT INTO mytable(id,name) VALUES ('BHF2552)6','3DRuczka.com');
INSERT INTO mytable(id,name) VALUES ('CYD3504$$','Router@Records');
INSERT INTO mytable(id,name) VALUES ('RJY8412)x','AAA.Battery.Solutions');
INSERT INTO mytable(id,name) VALUES ('HKT276!!y','Globe Corporation');