CREATE TABLE mytable(
   name         string
  ,organisation string
  ,budget       INTEGER
  ,status       string
);
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Echo Expansion','Orbital Systems',108150,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Vertex Expansion','TechCorp',437873,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Lyra Network','Skyline Industries',33951,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Horizon Program','CrystalPeak Institute',394094,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nimbus Protocol','TechCorp',51514,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Solara Platform','Orbital Systems',904703,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Vortex Program','Pioneer Group',451036,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Mirage Platform','FutureLabs',444598,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Helix Network','NovaWorks',189736,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Horizon Protocol','Pioneer Group',41953,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Lyra Protocol','TechCorp',53768,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Helix Project','CrystalPeak Institute',1966,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Lyra Program','TechCorp',185677,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Orion Protocol','Horizon Dynamics',416569,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Mirage System','Skyline Industries',650000,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Vortex Project','Orbital Systems',517819,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Titan Network','TechCorp',178607,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Vortex Platform','FutureLabs',69963,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nimbus System','Skyline Industries',706339,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Orion Project','NovaWorks',547949,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Phoenix System','BlueWave Foundation',444439,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Zenith System','Pioneer Group',850967,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Solara Initiative','Horizon Dynamics',197181,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nova Project','BlueWave Foundation',19131,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Orion Expansion','BlueWave Foundation',383353,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Titan Network','Orbital Systems',01997,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Zenith System','BlueWave Foundation',1340,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Apex Expansion','Skyline Industries',3174,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Spectra Program','TechCorp',785486,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Titan Network','FutureLabs',53655,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Pulse Initiative','FutureLabs',366480,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Echo Initiative','FutureLabs',411653,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Orion Platform','FutureLabs',637698,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nebula Program','TechCorp',666857,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Vortex Program','TechCorp',731599,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Mirage Expansion','Pioneer Group',31400,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nimbus Expansion','Horizon Dynamics',418675,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Phoenix Project','CrystalPeak Institute',66,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Pulse Program','TechCorp',67999,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Solara Network','SilverGate Consortium',500058,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Phoenix Protocol','Horizon Dynamics',13537,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Helix Project','CrystalPeak Institute',10757,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Apex System','Horizon Dynamics',796568,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nimbus System','Horizon Dynamics',896311,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nebula Expansion','BlueWave Foundation',138109,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Quantum Program','CrystalPeak Institute',79041,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Apex Program','Skyline Industries',737758,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nimbus Project','BlueWave Foundation',454399,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Solara Project','Pioneer Group',40617,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Phoenix Initiative','CrystalPeak Institute',997763,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nova Platform','TechCorp',735835,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Phoenix Program','NovaWorks',35953,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Echo System','Orbital Systems',443894,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Titan Expansion','FutureLabs',10783,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Vortex Network','BlueWave Foundation',390885,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Lyra Initiative','TechCorp',53674,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Lyra Platform','TechCorp',538598,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Orion Initiative','TechCorp',541914,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Lyra Program','CrystalPeak Institute',173614,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Solara Network','BlueWave Foundation',179044,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Spectra System','NovaWorks',33949,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Vortex Protocol','Horizon Dynamics',44807,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Pulse System','Horizon Dynamics',406774,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nova Project','Orbital Systems',049,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Zenith Platform','Orbital Systems',1443,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Solara Project','TechCorp',33876,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Helix Protocol','Horizon Dynamics',444516,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Vortex Platform','Horizon Dynamics',940848,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Phoenix System','FutureLabs',1185,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Vortex Protocol','Horizon Dynamics',669140,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nimbus Initiative','TechCorp',516158,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Mirage Platform','BlueWave Foundation',371894,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Echo Initiative','Horizon Dynamics',373355,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Mirage Network','NovaWorks',41453,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Lyra Platform','Pioneer Group',343110,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Mirage Initiative','Orbital Systems',0749,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Apex Program','Horizon Dynamics',384586,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Horizon Protocol','NovaWorks',406,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Astra Project','Horizon Dynamics',719149,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Lyra Platform','CrystalPeak Institute',05576,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Vertex Initiative','Orbital Systems',86033,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Solara Initiative','Horizon Dynamics',467333,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Vertex Platform','SilverGate Consortium',813047,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Titan System','Skyline Industries',19414,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Orion Project','FutureLabs',414154,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Zenith Platform','CrystalPeak Institute',58616,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Lyra Network','Pioneer Group',7506,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Phoenix Platform','FutureLabs',31716,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Phoenix Program','Pioneer Group',7336,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nebula System','Skyline Industries',439899,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Zenith System','BlueWave Foundation',65190,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Quantum Network','Horizon Dynamics',354186,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Horizon Expansion','NovaWorks',360714,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Vertex System','Orbital Systems',354038,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Horizon Protocol','BlueWave Foundation',413636,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Titan Project','FutureLabs',396360,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Lyra System','FutureLabs',58354,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nebula System','Horizon Dynamics',390433,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Helix Network','Skyline Industries',331753,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Horizon Expansion','FutureLabs',35355,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Phoenix Expansion','Horizon Dynamics',45958,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Titan Platform','CrystalPeak Institute',999686,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Apex Expansion','CrystalPeak Institute',43877,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Spectra Protocol','NovaWorks',43714,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Spectra Program','Pioneer Group',116464,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Apex Protocol','Orbital Systems',603763,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Spectra System','Orbital Systems',846194,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Orion Program','Orbital Systems',48763,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Solara Project','Horizon Dynamics',37300,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Vertex Network','Orbital Systems',477616,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Zenith Platform','TechCorp',491574,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Vortex Protocol','Pioneer Group',699395,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nimbus System','Orbital Systems',501851,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Linear Development','TechCorp',696969,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Apex Program','Horizon Dynamics',853656,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Helix Project','NovaWorks',1476,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Phoenix Protocol','FutureLabs',380130,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Vertex Expansion','Pioneer Group',856951,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Phoenix System','CrystalPeak Institute',347070,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Apex Program','CrystalPeak Institute',435679,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Zenith Protocol','Pioneer Group',77880,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Apex Expansion','TechCorp',373541,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Pulse Platform','TechCorp',959330,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Solara Project','SilverGate Consortium',567078,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Spectra Network','BlueWave Foundation',73710,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Quantum Entanglement','TechCorp',75640,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Helix Platform','BlueWave Foundation',89394,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Pulse Platform','FutureLabs',0699,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Echo Network','CrystalPeak Institute',65605,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nimbus Platform','Horizon Dynamics',83336,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Quantum Project','BlueWave Foundation',98875,'planned');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Apex Program','Pioneer Group',16555,'done');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Quantum Network','FutureLabs',100936,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Mirage Project','Horizon Dynamics',597808,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Solara Platform','SilverGate Consortium',17633,'active');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Nebula Protocol','CrystalPeak Institute',95613,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Lyra Program','Orbital Systems',464180,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Spectra Protocol','SilverGate Consortium',44545,'rejected');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Quantum Program','Pioneer Group',10531,'delayed');
INSERT INTO mytable(name,organisation,budget,status) VALUES ('Modern Warfare','TechCorp',8373,'delayed');
