CREATE TABLE national_bip(
   rating              float NOT NULL  
  ,name                text NOT NULL
  ,wojewodztwo         text NOT NULL
  ,number_of_employees INTEGER  NOT NULL
  ,taxes_paid          float NOT NULL
);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.8,'TechPol','Mazowieckie',50,1500000.50);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.2,'KopalniaPlus','Śląskie',100,9800000.00);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.6,'BalticTrade','Pomorskie',340,4300000.75);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.9,'AgroPol','Wielkopolskie',150,100000.10);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.5,'BuildMax','Małopolskie',430,300000.00);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.1,'MetalWorks','Podlaskie',0,1450000.33);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.7,'SpeedTrans','Łódzkie',610,780000.90);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.3,'GreenFarm','Podkarpackie',85,670000.45);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.9,'NeoIT','Mazowieckie',890,15400000.00);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.8,'RiverLogistics','Kujawsko-Pomorskie',300,100000.44);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.0,'AutoSerwisPlus','Lubelskie',55,30000.1);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.4,'CloudVision','Mazowieckie',410,9600000.30);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.6,'EuroSteel','Śląskie',1300,1100000.70);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.7,'SoftVision','Wielkopolskie',760,13900000.0);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.5,'SunGarden','Lubuskie',40,150000.00);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.8,'FinTechNow','Mazowieckie',540,1300000.);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.9,'ChemPol','Opolskie',90,190000.10);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.3,'NanoTech','Małopolskie',380,8300000.55);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.1,'FoodFarm','Pomorskie',10,600000.00);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.6,'OceanLine','Pomorskie',760,5400000.80);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.8,'GeoMining','Świętokrzyskie',510,3100000.10);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.5,'ElektroMax','Mazowieckie',300,8700000.00);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.7,'AutoParts','Śląskie',440,400000.75);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.2,'MedTech','Łódzkie',60,900000.31);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.4,'ProEdu','Podlaskie',75,450000.5);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.0,'FarmaLux','Warmińsko-Mazurskie',95,370000.60);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.9,'RoboticsAI','Mazowieckie',970,18400000.50);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.6,'FastPrint','Mazowieckie',48,00000.00);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.1,'StoneBuild','Małopolskie',180,100000.45);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.3,'TechSystems','Wielkopolskie',510,6500000.90);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.9,'OptiGlass','Lubelskie',130,580000.33);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.7,'ModeDesign','Łódzkie',60,4100000.55);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.8,'EcoLine','Podkarpackie',7,330000.11);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.5,'AutoDrive','Śląskie',830,11900000.00);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.2,'MetroIT','Mazowieckie',350,7600000.66);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.7,'FreshFood','Małopolskie',10,980000.77);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.1,'BioHerbs','Podlaskie',44,160000.45);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.3,'ShipyardPro','Pomorskie',150,14300000.90);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.5,'TermoHeat','Opolskie',140,430000.00);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.6,'BrightEnergy','Lubelskie',50,5700000.10);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.9,'WhiteLogistics','Warmińsko-Mazurskie',330,100000.3);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.4,'MobileApps','Mazowieckie',410,700000.44);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.8,'SecureIT','Małopolskie',790,1600000.10);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.6,'GreenHouse','Lubuskie',5,180000.00);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.2,'SteelArt','Śląskie',1010,11800000.66);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.1,'PharmaPlus','Łódzkie',340,5400000.19);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.5,'SoftStar','Mazowieckie',60,1350000.75);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.8,'EcoResources','Podkarpackie',88,40000.);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.0,'GranitePol','Świętokrzyskie',10,900000.99);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.7,'BioLab','Wielkopolskie',430,6900000.55);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.9,'PrecisionTools','Małopolskie',305,600000.10);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.3,'BlueOcean','Pomorskie',880,7400000.80);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.7,'AgroMax','Lubelskie',140,350000.60);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.6,'VectorTech','Mazowieckie',70,15100000.0);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.4,'PrintHouse','Podlaskie',64,40000.30);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.8,'AutoLine','Śląskie',550,800000.10);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.9,'CloudNet','Mazowieckie',990,1000000.40);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.6,'BuildNow','Kujawsko-Pomorskie',18,540000.55);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.2,'GreenEnergy','Pomorskie',440,500000.1);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.5,'SmartRobotics','Łódzkie',580,9000000.40);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.7,'FinPro','Mazowieckie',730,13000000.10);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.9,'WoodCraft','Podkarpackie',11,410000.4);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.1,'StoneTech','Opolskie',60,1400000.14);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.3,'MegaTransport','Wielkopolskie',780,600000.90);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.0,'LightBuild','Małopolskie',150,680000.10);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.8,'NextGenIT','Mazowieckie',850,1600000.50);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.7,'PaperMax','Lubelskie',1,300000.33);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.6,'ShipPro','Pomorskie',130,1500000.10);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('TechCorp',4.9,'Dolnośląskie',340,3500000.69);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.5,'EcoFarm','Warmińsko-Mazurskie',60,10000.00);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.4,'TechSpeed','Śląskie',480,3300000.35);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.2,'MediaSoft','Mazowieckie',390,7400000.40);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.8,'FoodLine','Świętokrzyskie',95,50000.00);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.5,'AutoPartsPlus','Łódzkie',860,1000000.70);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.7,'SmartIT','Małopolskie',510,8400000.55);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.9,'GreenMining','Lubuskie',14,540000.00);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.1,'ProSteel','Opolskie',80,1700000.33);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.6,'AIWorks','Mazowieckie',900,17500000.);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.8,'SoftMedia','Wielkopolskie',310,100000.50);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.4,'AgroPlus','Podlaskie',78,380000.77);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.0,'BoltTrans','Kujawsko-Pomorskie',60,100000.0);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.3,'ClearIT','Mazowieckie',440,8100000.55);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.7,'HeatSystems','Śląskie',690,4100000.00);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.8,'DeepTech','Małopolskie',880,16300000.90);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.6,'PolForest','Warmińsko-Mazurskie',7,60000.);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.1,'PaperPlus','Pomorskie',430,3500000.44);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.5,'SolarWave','Lubelskie',380,5100000.10);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.9,'DataAI','Mazowieckie',1040,800000.75);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.8,'ChemIndustry','Opolskie',330,1600000.66);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.2,'NextSoft','Wielkopolskie',700,9000000.10);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.9,'RoadBuild','Małopolskie',10,70000.3);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.6,'BlueTech','Pomorskie',840,9900000.11);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.4,'FreshMarket','Świętokrzyskie',105,430000.0);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (3.7,'LaserTools','Podkarpackie',95,310000.33);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.3,'FutureIT','Łódzkie',650,1000000.70);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.8,'HyperCloud','Mazowieckie',1150,6000000.0);
INSERT INTO national_bip(rating,name,wojewodztwo,number_of_employees,taxes_paid) VALUES (4.0,'GreenStone','Lubuskie',55,180000.50);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('DolTech Solutions',4.6,'Dolnośląskie',50,8700000.4);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('Silesia Robotics',4.3,'Dolnośląskie',310,4100000.1);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('WroSoft Innovations',4.7,'Dolnośląskie',780,1000000.5);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('LowerSilesia Logistics',4.1,'Dolnośląskie',460,300000.44);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('GreenPower Dolny Śląsk',4.5,'Dolnośląskie',30,900000.0);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('NanoWroc Technologies',4.4,'Dolnośląskie',360,5100000.88);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('AutoCraft DS',4.2,'Dolnośląskie',190,1800000.);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('MetalExpert Wrocław',4.0,'Dolnośląskie',980,9500000.1);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('BioMedica Dolnośląska',4.6,'Dolnośląskie',540,700000.6);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('DeepVision Labs',4.8,'Dolnośląskie',110,16500000.);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('Sudecka Fabryka Druku 3D',4.3,'Dolnośląskie',40,3300000.55);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('SmartEnergy Wrocław',4.5,'Dolnośląskie',480,6900000.0);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('TechWave DS',4.4,'Dolnośląskie',350,5700000.9);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('Wrocław Automation',4.2,'Dolnośląskie',410,4100000.1);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('BlueData Analytics',4.7,'Dolnośląskie',660,10500000.4);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('AgroFuture Dolny Śląsk',4.1,'Dolnośląskie',10,980000.1);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('Precision MetalWorks DS',4.0,'Dolnośląskie',760,600000.0);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('Silesia PharmaLab',4.5,'Dolnośląskie',370,5600000.33);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('EcoStone Engineering',4.3,'Dolnośląskie',10,700000.);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('SolarVision Wrocław',4.8,'Dolnośląskie',900,14000000.8);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('Dolnośląski Instytut IT',4.6,'Dolnośląskie',690,9500000.3);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('CrystalGlass Tech',4.4,'Dolnośląskie',150,100000.15);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('GreenForest BioTech',4.2,'Dolnośląskie',180,1600000.1);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('FutureSteel DS',4.1,'Dolnośląskie',80,700000.77);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('WroCyber Security',4.7,'Dolnośląskie',850,14800000.);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('QuantumSoft Dolny Śląsk',4.8,'Dolnośląskie',100,17500000.5);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('BlackMountain Logistics',4.0,'Dolnośląskie',610,3300000.);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('BioFresh Solutions',4.3,'Dolnośląskie',140,1700000.4);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('LowerSilesia AI Center',4.6,'Dolnośląskie',880,1500000.75);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('EcoFarmTech DS',4.2,'Dolnośląskie',00,1400000.3);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('Wroclaw DroneWorks',4.5,'Dolnośląskie',330,4300000.33);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('SteelArt Dolny Śląsk',4.1,'Dolnośląskie',500,900000.55);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('NanoBuild Engineering',4.4,'Dolnośląskie',310,3600000.1);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('GreenLine Mobility',4.3,'Dolnośląskie',40,500000.0);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('DeepAI Systems DS',4.7,'Dolnośląskie',70,1300000.4);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('LowerSilesia Energy Hub',4.5,'Dolnośląskie',640,8800000.33);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('Silesia Optics Lab',4.2,'Dolnośląskie',130,100000.5);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('WroTech Motors',4.1,'Dolnośląskie',950,8300000.1);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('CloudMatrix Dolnośląskie',4.6,'Dolnośląskie',870,1500000.4);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('Quantum Robotics DS',4.8,'Dolnośląskie',1110,16400000.88);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('Silesia AgroLab',4.0,'Dolnośląskie',95,800000.1);
INSERT INTO national_bip(name,rating,wojewodztwo,number_of_employees,taxes_paid) VALUES ('Wrocław Engineering Group',4.3,'Dolnośląskie',40,3400000.66);

