tasks = [
    {"id": 1, "name": "Pomoc w bibliotece", "time": 15, "points": 50},
    {"id": 2, "name": "Sprzątanie parku", "time": 22, "points": 70},
    {"id": 3, "name": "Opieka nad zwierzętami", "time": 10, "points": 35},
    {"id": 4, "name": "Pomoc seniorom", "time": 12, "points": 45},
    {"id": 5, "name": "Nauka dzieci", "time": 20, "points": 65},
    {"id": 6, "name": "Segregacja odpadów", "time": 8, "points": 25},
    {"id": 7, "name": "Wsparcie jadłodajni", "time": 18, "points": 55},
    {"id": 8, "name": "Sadzenie drzew", "time": 25, "points": 80},
    {"id": 9, "name": "Organizacja zbiórki", "time": 10, "points": 30},
    {"id": 10, "name": "Wolontariat szpitalny", "time": 30, "points": 95},
    {"id": 11, "name": "Malowanie muralu", "time": 28, "points": 85},
    {"id": 12, "name": "Pomoc bezdomnym", "time": 15, "points": 50},
    {"id": 13, "name": "Naprawa ławek", "time": 20, "points": 60},
    {"id": 14, "name": "Prowadzenie warsztatu", "time": 22, "points": 75},
    {"id": 15, "name": "Sprzątanie plaży", "time": 18, "points": 55},
    {"id": 16, "name": "Pomoc w schronisku", "time": 12, "points": 40},
    {"id": 17, "name": "Czytanie dzieciom", "time": 10, "points": 35},
    {"id": 18, "name": "Transport seniorów", "time": 15, "points": 45},
    {"id": 19, "name": "Organizacja festynu", "time": 30, "points": 100},
    {"id": 20, "name": "Renowacja placu zabaw", "time": 25, "points": 75},
    {"id": 21, "name": "Pomoc w zbiorach", "time": 20, "points": 60},
    {"id": 22, "name": "Recykling elektroniki", "time": 8, "points": 20},
    {"id": 23, "name": "Opieka nad ogrodem", "time": 18, "points": 50},
    {"id": 24, "name": "Kurs pierwszej pomocy", "time": 22, "points": 70},
    {"id": 25, "name": "Wsparcie imigrantów", "time": 15, "points": 55},
    {"id": 26, "name": "Spacery z psami", "time": 10, "points": 30},
    {"id": 27, "name": "Malowanie szkoły", "time": 28, "points": 80},
    {"id": 28, "name": "Sortowanie darów", "time": 12, "points": 35},
    {"id": 29, "name": "Remont świetlicy", "time": 25, "points": 75},
    {"id": 30, "name": "Pomoc techniczna IT", "time": 15, "points": 50},
    {"id": 31, "name": "Nauka języka obcego", "time": 20, "points": 65},
    {"id": 32, "name": "Sprzątanie lasu", "time": 22, "points": 70},
    {"id": 33, "name": "Budowa domków dla ptaków", "time": 12, "points": 40},
    {"id": 34, "name": "Pomoc w archiwum", "time": 10, "points": 30},
    {"id": 35, "name": "Coaching zawodowy", "time": 18, "points": 60},
    {"id": 36, "name": "Naprawa rowerów", "time": 15, "points": 45},
    {"id": 37, "name": "Organizacja koncertu", "time": 28, "points": 90},
    {"id": 38, "name": "Tworzenie strony WWW", "time": 20, "points": 70},
    {"id": 39, "name": "Pomoc w muzeum", "time": 12, "points": 40},
    {"id": 40, "name": "Prowadzenie bloga", "time": 8, "points": 25},
]